version: "3.1"

services:
  db:
    container_name: apollo-server-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=apollo-server
    ports:
      - 27017:27017
